name: Deploy
on:
  push:
    branches:
      - main

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install Node
      run: |
        curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
        npm install -g npm pnpm
        node --version

    - name: Build, Test, Publish
      run: |
        make build
        make test

      env:
        CI: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}